language: nix
sudo: false
script: nix-shell -p nix-prefetch-scripts --run "./suite.sh --trace"
matrix:
    include:
        - os: linux
          dist: trusty
          env: PATH=$PATH:.:..
notifications:
    email:
        on_success: never
        on_failure: change
